author: mrmag518
main: com.mrmag518.spawnergui.Main
version: '1.9.1'
name: SpawnerGUI
description: "Simple & easy spawner modification GUI."
softdepend: [Vault, WorldGuard]
commands:
  spawnergui:
    description: Reload SpawnerGUI.
    usage: /<command>
permissions:
  spawnergui.open:
    default: op
  spawnergui.eco.bypass.*:
    default: op
  spawnergui.edit.*:
    default: op
  spawnergui.command.reload:
    default: op