author: mrmag518
main: com.mrmag518.SpawnerGUI.SpawnerGUI
version: '1.6'
name: SpawnerGUI
description: "Simple & easy spawner modification GUI."
softdepend: [Vault]
commands:
  spawnergui:
    description: Main command for SpawnerGUI.
    usage: /<command>
permissions:
  spawnergui.open:
    default: op
  spawnergui.eco.bypass.*:
    default: op
  spawnergui.edit.*:
    default: false